### ISSUE TITLE
Readme: jackson-javax-json is unsupported

### ISSUE THREAD

**Issue by adamu** [FasterXML/jackson-datatype-jsr353#15]
The recommended JSR-353 library in the readme has been unsupported since [at least 30 July 2019](https://github.com/pgelinas/jackson-javax-json/commit/f2d43c5b6e1ef5b3e184d3ce9f6efd577d75f27c).

https://github.com/pgelinas/jackson-javax-json

**Comment by cowtowncoder** [comment]
Thanks, I'll add a note on its status (and/or rewrite reference somehow to indicate that).
