### ISSUE TITLE
Null being deserialized as null literal instead of JsonValue.NULL

### ISSUE THREAD

**Issue by marcospassos** [FasterXML/jackson-datatype-jsr353#16]
The deserializer is deserializing null literally instead of `JsonValue.NULL`.

**Comment by cowtowncoder** [comment]
Any chance for a small reproduction? :)

**Comment by marcospassos** [comment]
@cowtowncoder Thanks your quick reply. I've just submitted a PR that includes the test and fix for the issue.

**Comment by cowtowncoder** [comment]
Alas, need to revert due to #18, for 2.10.5.
