### ISSUE TITLE
Link to jackson-javax-json is broken in Readme.md

### ISSUE THREAD

**Issue by lefe** [FasterXML/jackson-datatype-jsr353#8]
Broken:

https://github.com/FasterXML/pgelinas/jackson-javax-json

Actual:

https://github.com/pgelinas/jackson-javax-json

**Comment by cowtowncoder** [comment]
Thanks! Looks like one of links was broken.

**Comment by basil-bourque** [comment]
Also, the README.md has a broken link to
http://jackson.codehaus.org/ that should be 
https://github.com/FasterXML/jackson.
